name: project-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - tensorflow=2.16
  - numpy=1.25
  - matplotlib
  - opencv
  # Note: don't pin cudatoolkit or cudnn here. Using conda-forge's tensorflow will
  # pull compatible cuDNN/CUDA versions automatically for the environment.
  - pip:
    - requests
